export interface ActividadEconomica {
  codigo: string;
  descripcion: string;
}

export const CATALOG_META_ACTIVIDADES = {
  fuente: 'Ministerio de Hacienda SV - Catalogo Sistema de Transmision',
  version: '1.2 (10/2025)',
  catalogo: 'CAT-019',
  actualizado: '2026-04-20',
  nota: 'Listado interno normalizado para uso operativo en formularios iFactu.',
} as const;

// Catalogo CAT-019 del MH El Salvador (actividades economicas CIIU Rev.4)
export const ACTIVIDADES_ECONOMICAS: ActividadEconomica[] = [
  // Agricultura, ganadería
  { codigo: '01111', descripcion: 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas' },
  { codigo: '01120', descripcion: 'Cultivo de arroz' },
  { codigo: '01130', descripcion: 'Cultivo de hortalizas y melones, raíces y tubérculos' },
  { codigo: '01140', descripcion: 'Cultivo de caña de azúcar' },
  { codigo: '01150', descripcion: 'Cultivo de tabaco' },
  { codigo: '01160', descripcion: 'Cultivo de plantas de fibra' },
  { codigo: '01210', descripcion: 'Cultivo de uva' },
  { codigo: '01220', descripcion: 'Cultivo de frutas tropicales y subtropicales' },
  { codigo: '01230', descripcion: 'Cultivo de cítricos' },
  { codigo: '01270', descripcion: 'Cultivo de plantas con las que se preparan bebidas' },
  { codigo: '01280', descripcion: 'Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas' },
  { codigo: '01410', descripcion: 'Cría de ganado bovino y búfalos' },
  { codigo: '01420', descripcion: 'Cría de caballos y otros equinos' },
  { codigo: '01440', descripcion: 'Cría de ovejas y cabras' },
  { codigo: '01450', descripcion: 'Cría de cerdos' },
  { codigo: '01460', descripcion: 'Cría de aves de corral' },
  { codigo: '01500', descripcion: 'Cultivo de productos agrícolas en combinación con la cría de animales' },
  // Pesca
  { codigo: '03110', descripcion: 'Pesca marítima' },
  { codigo: '03120', descripcion: 'Pesca en agua dulce' },
  { codigo: '03210', descripcion: 'Acuicultura marítima' },
  { codigo: '03220', descripcion: 'Acuicultura en agua dulce' },
  // Industria manufacturera
  { codigo: '10110', descripcion: 'Procesamiento y conservación de carne' },
  { codigo: '10120', descripcion: 'Procesamiento y conservación de carne de aves' },
  { codigo: '10200', descripcion: 'Procesamiento y conservación de pescado' },
  { codigo: '10310', descripcion: 'Elaboración y conservación de frutas' },
  { codigo: '10320', descripcion: 'Elaboración de jugos de frutas y verduras' },
  { codigo: '10390', descripcion: 'Elaboración y conservación de otros alimentos' },
  { codigo: '10410', descripcion: 'Elaboración de aceites y grasas de origen vegetal' },
  { codigo: '10420', descripcion: 'Elaboración de margarina y grasas comestibles similares' },
  { codigo: '10430', descripcion: 'Elaboración de aceites y grasas de origen animal' },
  { codigo: '10510', descripcion: 'Elaboración de productos lácteos' },
  { codigo: '10611', descripcion: 'Molinería de trigo' },
  { codigo: '10612', descripcion: 'Molinería de maíz' },
  { codigo: '10620', descripcion: 'Elaboración de almidones y productos derivados' },
  { codigo: '10710', descripcion: 'Elaboración de productos de panadería' },
  { codigo: '10720', descripcion: 'Elaboración de azúcar' },
  { codigo: '10730', descripcion: 'Elaboración de cacao, chocolate y productos de confitería' },
  { codigo: '10740', descripcion: 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos' },
  { codigo: '10750', descripcion: 'Elaboración de comidas y platos preparados' },
  { codigo: '10790', descripcion: 'Elaboración de otros productos alimenticios' },
  { codigo: '10800', descripcion: 'Elaboración de alimentos preparados para animales' },
  { codigo: '11010', descripcion: 'Destilación, rectificación y mezcla de bebidas alcohólicas' },
  { codigo: '11020', descripcion: 'Elaboración de vinos' },
  { codigo: '11030', descripcion: 'Elaboración de bebidas malteadas y de malta' },
  { codigo: '11040', descripcion: 'Elaboración de bebidas no alcohólicas' },
  { codigo: '12000', descripcion: 'Elaboración de productos de tabaco' },
  { codigo: '13100', descripcion: 'Preparación e hilatura de fibras textiles' },
  { codigo: '13200', descripcion: 'Tejedura de productos textiles' },
  { codigo: '14100', descripcion: 'Fabricación de prendas de vestir' },
  { codigo: '14200', descripcion: 'Fabricación de artículos de piel' },
  { codigo: '15110', descripcion: 'Curtido y adobo de cueros' },
  { codigo: '15120', descripcion: 'Fabricación de maletas, bolsos de mano y artículos similares' },
  { codigo: '15200', descripcion: 'Fabricación de calzado' },
  { codigo: '16100', descripcion: 'Aserrado y acepillado de madera' },
  { codigo: '16210', descripcion: 'Fabricación de hojas de madera para enchapado' },
  { codigo: '16220', descripcion: 'Fabricación de partes y piezas de carpintería para edificios y construcciones' },
  { codigo: '17110', descripcion: 'Fabricación de pasta de madera, papel y cartón' },
  { codigo: '17120', descripcion: 'Fabricación de papel y cartón ondulado y envases' },
  { codigo: '18110', descripcion: 'Impresión' },
  { codigo: '18120', descripcion: 'Actividades de servicios relacionadas con la impresión' },
  { codigo: '20110', descripcion: 'Fabricación de gases industriales' },
  { codigo: '20120', descripcion: 'Fabricación de colorantes y pigmentos' },
  { codigo: '20130', descripcion: 'Fabricación de otros productos químicos inorgánicos básicos' },
  { codigo: '20200', descripcion: 'Fabricación de plaguicidas y otros productos agroquímicos' },
  { codigo: '20300', descripcion: 'Fabricación de pinturas, barnices y productos de revestimiento' },
  { codigo: '20410', descripcion: 'Fabricación de jabones y detergentes' },
  { codigo: '20420', descripcion: 'Fabricación de perfumes y preparados de tocador' },
  { codigo: '20510', descripcion: 'Fabricación de productos explosivos' },
  { codigo: '20520', descripcion: 'Fabricación de colas' },
  { codigo: '21000', descripcion: 'Fabricación de productos farmacéuticos' },
  { codigo: '22110', descripcion: 'Fabricación de cubiertas y cámaras de caucho' },
  { codigo: '22190', descripcion: 'Fabricación de otros productos de caucho' },
  { codigo: '22200', descripcion: 'Fabricación de productos de plástico' },
  { codigo: '23100', descripcion: 'Fabricación de vidrio y productos de vidrio' },
  { codigo: '23910', descripcion: 'Fabricación de productos abrasivos' },
  { codigo: '24100', descripcion: 'Industrias básicas de hierro y acero' },
  { codigo: '24200', descripcion: 'Fabricación de productos primarios de metales preciosos' },
  { codigo: '25110', descripcion: 'Fabricación de estructuras metálicas y sus partes' },
  { codigo: '25120', descripcion: 'Fabricación de tanques, depósitos y recipientes de metal' },
  { codigo: '25200', descripcion: 'Fabricación de armas y municiones' },
  { codigo: '25300', descripcion: 'Forja, prensado, estampado y laminado de metales' },
  { codigo: '25400', descripcion: 'Tratamiento y revestimiento de metales' },
  { codigo: '25910', descripcion: 'Fabricación de productos metálicos para uso estructural' },
  { codigo: '26100', descripcion: 'Fabricación de componentes y tableros electrónicos' },
  { codigo: '26200', descripcion: 'Fabricación de computadoras y equipo periférico' },
  { codigo: '26300', descripcion: 'Fabricación de equipos de comunicaciones' },
  { codigo: '26400', descripcion: 'Fabricación de aparatos electrónicos de consumo' },
  { codigo: '27100', descripcion: 'Fabricación de motores, generadores y transformadores eléctricos' },
  { codigo: '27200', descripcion: 'Fabricación de pilas y acumuladores eléctricos' },
  { codigo: '27400', descripcion: 'Fabricación de equipos de iluminación eléctrica' },
  { codigo: '27500', descripcion: 'Fabricación de aparatos de uso doméstico' },
  { codigo: '28110', descripcion: 'Fabricación de motores y turbinas' },
  { codigo: '28150', descripcion: 'Fabricación de cojinetes, engranajes y elementos de transmisión' },
  { codigo: '28180', descripcion: 'Fabricación de maquinaria de uso general' },
  { codigo: '29100', descripcion: 'Fabricación de vehículos automotores' },
  { codigo: '29200', descripcion: 'Fabricación de carrocerías para vehículos automotores' },
  { codigo: '29300', descripcion: 'Fabricación de partes y accesorios para vehículos automotores' },
  // Construcción
  { codigo: '41001', descripcion: 'Construcción de edificios residenciales' },
  { codigo: '41002', descripcion: 'Construcción de edificios no residenciales' },
  { codigo: '42101', descripcion: 'Construcción de carreteras y autopistas' },
  { codigo: '42102', descripcion: 'Construcción de vías de ferrocarril' },
  { codigo: '43110', descripcion: 'Demolición' },
  { codigo: '43120', descripcion: 'Preparación del terreno' },
  { codigo: '43210', descripcion: 'Instalaciones eléctricas' },
  { codigo: '43220', descripcion: 'Fontanería, instalaciones de calefacción y aire acondicionado' },
  { codigo: '43290', descripcion: 'Otras instalaciones para obras de construcción' },
  { codigo: '43300', descripcion: 'Terminación y acabado de edificios' },
  // Comercio
  { codigo: '45101', descripcion: 'Venta de vehículos automotores nuevos' },
  { codigo: '45102', descripcion: 'Venta de vehículos automotores usados' },
  { codigo: '45200', descripcion: 'Mantenimiento y reparación de vehículos automotores' },
  { codigo: '45301', descripcion: 'Venta al por mayor de repuestos y accesorios de vehículos' },
  { codigo: '45302', descripcion: 'Venta al por menor de repuestos y accesorios de vehículos' },
  { codigo: '46100', descripcion: 'Venta al por mayor a cambio de una retribución o por contrato' },
  { codigo: '46110', descripcion: 'Agentes que intervienen en la venta de productos agropecuarios' },
  { codigo: '46120', descripcion: 'Agentes que intervienen en la venta de combustibles' },
  { codigo: '46130', descripcion: 'Agentes que intervienen en la venta de madera y materiales de construcción' },
  { codigo: '46190', descripcion: 'Otros agentes que intervienen en la venta de productos variados' },
  { codigo: '46200', descripcion: 'Venta al por mayor de materias primas agropecuarias y animales vivos' },
  { codigo: '46310', descripcion: 'Venta al por mayor de frutas y verduras' },
  { codigo: '46320', descripcion: 'Venta al por mayor de carne y productos cárnicos' },
  { codigo: '46330', descripcion: 'Venta al por mayor de productos lácteos, huevos y aceites' },
  { codigo: '46340', descripcion: 'Venta al por mayor de bebidas' },
  { codigo: '46350', descripcion: 'Venta al por mayor de tabaco' },
  { codigo: '46360', descripcion: 'Venta al por mayor de azúcar, chocolate y confitería' },
  { codigo: '46390', descripcion: 'Venta al por mayor de otros alimentos' },
  { codigo: '46410', descripcion: 'Venta al por mayor de hilados, telas y artículos de mercería' },
  { codigo: '46420', descripcion: 'Venta al por mayor de prendas de vestir y calzado' },
  { codigo: '46491', descripcion: 'Venta al por mayor de artículos de ferretería' },
  { codigo: '46492', descripcion: 'Venta al por mayor de materiales de construcción' },
  { codigo: '46510', descripcion: 'Venta al por mayor de computadoras y equipo periférico' },
  { codigo: '46520', descripcion: 'Venta al por mayor de equipos electrónicos y de telecomunicaciones' },
  { codigo: '46610', descripcion: 'Venta al por mayor de maquinaria agrícola' },
  { codigo: '46620', descripcion: 'Venta al por mayor de máquinas herramienta' },
  { codigo: '46630', descripcion: 'Venta al por mayor de maquinaria para minería y construcción' },
  { codigo: '46690', descripcion: 'Venta al por mayor de otros tipos de maquinaria y equipo' },
  { codigo: '46710', descripcion: 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos' },
  { codigo: '46720', descripcion: 'Venta al por mayor de metales y minerales metalíferos' },
  { codigo: '46730', descripcion: 'Venta al por mayor de madera, materiales de construcción' },
  { codigo: '46900', descripcion: 'Venta al por mayor de otros productos' },
  { codigo: '47110', descripcion: 'Venta al por menor en comercios no especializados con predominio de alimentos' },
  { codigo: '47190', descripcion: 'Venta al por menor de otros productos en comercios no especializados' },
  { codigo: '47210', descripcion: 'Venta al por menor de frutas y verduras' },
  { codigo: '47220', descripcion: 'Venta al por menor de carne y productos cárnicos' },
  { codigo: '47230', descripcion: 'Venta al por menor de pescado' },
  { codigo: '47240', descripcion: 'Venta al por menor de pan y productos de panadería' },
  { codigo: '47250', descripcion: 'Venta al por menor de bebidas' },
  { codigo: '47260', descripcion: 'Venta al por menor de tabaco' },
  { codigo: '47290', descripcion: 'Venta al por menor de otros alimentos en comercios especializados' },
  { codigo: '47300', descripcion: 'Venta al por menor de combustibles para vehículos automotores' },
  { codigo: '47410', descripcion: 'Venta al por menor de computadoras, equipo periférico y software' },
  { codigo: '47420', descripcion: 'Venta al por menor de equipos de telecomunicaciones' },
  { codigo: '47430', descripcion: 'Venta al por menor de equipos de audio y video' },
  { codigo: '47510', descripcion: 'Venta al por menor de productos textiles' },
  { codigo: '47520', descripcion: 'Venta al por menor de artículos de ferretería' },
  { codigo: '47530', descripcion: 'Venta al por menor de tapices, alfombras y recubrimientos' },
  { codigo: '47540', descripcion: 'Venta al por menor de electrodomésticos' },
  { codigo: '47590', descripcion: 'Venta al por menor de muebles, equipos de iluminación y artículos del hogar' },
  { codigo: '47610', descripcion: 'Venta al por menor de libros, periódicos y artículos de papelería' },
  { codigo: '47620', descripcion: 'Venta al por menor de grabaciones de música y de video' },
  { codigo: '47630', descripcion: 'Venta al por menor de equipo de deporte' },
  { codigo: '47640', descripcion: 'Venta al por menor de juegos y juguetes' },
  { codigo: '47710', descripcion: 'Venta al por menor de prendas de vestir' },
  { codigo: '47720', descripcion: 'Venta al por menor de calzado y artículos de cuero' },
  { codigo: '47730', descripcion: 'Venta al por menor de productos farmacéuticos y medicinales' },
  { codigo: '47740', descripcion: 'Venta al por menor de artículos médicos y ortopédicos' },
  { codigo: '47750', descripcion: 'Venta al por menor de cosméticos y artículos de tocador' },
  { codigo: '47760', descripcion: 'Venta al por menor de flores, plantas, semillas y fertilizantes' },
  { codigo: '47770', descripcion: 'Venta al por menor de artículos de relojería y joyería' },
  { codigo: '47780', descripcion: 'Venta al por menor de otros productos nuevos en comercios especializados' },
  { codigo: '47810', descripcion: 'Venta al por menor de alimentos, bebidas y tabaco en puestos y mercados' },
  { codigo: '47820', descripcion: 'Venta al por menor de productos textiles en puestos y mercados' },
  { codigo: '47890', descripcion: 'Venta al por menor de otros productos en puestos y mercados' },
  { codigo: '47910', descripcion: 'Venta al por menor por correo y por Internet' },
  { codigo: '47990', descripcion: 'Venta al por menor no realizada en comercios, puestos de venta o mercados' },
  // Transporte
  { codigo: '49100', descripcion: 'Transporte por ferrocarril' },
  { codigo: '49210', descripcion: 'Transporte urbano y suburbano de pasajeros' },
  { codigo: '49220', descripcion: 'Transporte de pasajeros por taxi' },
  { codigo: '49230', descripcion: 'Otros tipos de transporte por vía terrestre de pasajeros' },
  { codigo: '49310', descripcion: 'Transporte de carga por carretera' },
  { codigo: '50100', descripcion: 'Transporte marítimo y de cabotaje' },
  { codigo: '51100', descripcion: 'Transporte aéreo de pasajeros' },
  { codigo: '51200', descripcion: 'Transporte aéreo de carga' },
  { codigo: '52100', descripcion: 'Almacenamiento y depósito' },
  { codigo: '52210', descripcion: 'Actividades de servicios vinculadas al transporte terrestre' },
  { codigo: '52220', descripcion: 'Actividades de servicios vinculadas al transporte acuático' },
  { codigo: '52230', descripcion: 'Actividades de servicios vinculadas al transporte aéreo' },
  { codigo: '52240', descripcion: 'Manipulación de la carga' },
  { codigo: '52290', descripcion: 'Otras actividades de apoyo al transporte' },
  { codigo: '53100', descripcion: 'Actividades postales' },
  { codigo: '53200', descripcion: 'Actividades de mensajería' },
  // Alojamiento y restaurantes
  { codigo: '55100', descripcion: 'Actividades de los hoteles y alojamientos similares' },
  { codigo: '55200', descripcion: 'Actividades de campamentos, parques de vehículos recreativos y otros' },
  { codigo: '55900', descripcion: 'Otras actividades de alojamiento' },
  { codigo: '56100', descripcion: 'Actividades de restaurantes y de servicio móvil de comidas' },
  { codigo: '56210', descripcion: 'Suministro de comidas por encargo' },
  { codigo: '56290', descripcion: 'Otras actividades de servicio de comidas' },
  { codigo: '56300', descripcion: 'Actividades de servicio de bebidas' },
  // Información y comunicaciones
  { codigo: '58110', descripcion: 'Edición de libros' },
  { codigo: '58120', descripcion: 'Edición de directorios y listas de correo' },
  { codigo: '58130', descripcion: 'Edición de periódicos, revistas y otras publicaciones periódicas' },
  { codigo: '58190', descripcion: 'Otras actividades de edición' },
  { codigo: '58200', descripcion: 'Edición de programas informáticos' },
  { codigo: '59110', descripcion: 'Actividades de producción de películas cinematográficas' },
  { codigo: '59200', descripcion: 'Actividades de grabación de sonido y edición de música' },
  { codigo: '60100', descripcion: 'Transmisión de radio' },
  { codigo: '60200', descripcion: 'Programación y transmisión de televisión' },
  { codigo: '61100', descripcion: 'Actividades de telecomunicaciones alámbrica' },
  { codigo: '61200', descripcion: 'Actividades de telecomunicaciones inalámbrica' },
  { codigo: '61300', descripcion: 'Actividades de telecomunicaciones por satélite' },
  { codigo: '61900', descripcion: 'Otras actividades de telecomunicaciones' },
  { codigo: '62010', descripcion: 'Actividades de programación informática' },
  { codigo: '62020', descripcion: 'Actividades de consultoría informática' },
  { codigo: '62030', descripcion: 'Gestión de recursos informáticos' },
  { codigo: '62090', descripcion: 'Otras actividades de tecnología de la información' },
  { codigo: '63110', descripcion: 'Procesamiento de datos, hospedaje y actividades conexas' },
  { codigo: '63120', descripcion: 'Portales web' },
  { codigo: '63910', descripcion: 'Actividades de agencias de noticias' },
  { codigo: '63990', descripcion: 'Otras actividades de servicios de información' },
  // Actividades financieras
  { codigo: '64110', descripcion: 'Actividades del banco central' },
  { codigo: '64190', descripcion: 'Otros tipos de intermediación monetaria' },
  { codigo: '64200', descripcion: 'Actividades de sociedades de cartera' },
  { codigo: '64300', descripcion: 'Fondos y sociedades de inversión y entidades financieras similares' },
  { codigo: '64910', descripcion: 'Arrendamiento financiero' },
  { codigo: '64920', descripcion: 'Otras actividades de concesión de crédito' },
  { codigo: '64990', descripcion: 'Otras actividades de servicios financieros' },
  { codigo: '65110', descripcion: 'Seguros de vida' },
  { codigo: '65120', descripcion: 'Seguros generales' },
  { codigo: '65200', descripcion: 'Reaseguros' },
  { codigo: '65300', descripcion: 'Fondos de pensiones' },
  { codigo: '66110', descripcion: 'Administración de mercados financieros' },
  { codigo: '66120', descripcion: 'Actividades de negociación de contratos de productos básicos' },
  { codigo: '66190', descripcion: 'Otras actividades auxiliares de las actividades de servicios financieros' },
  { codigo: '66210', descripcion: 'Actividades de evaluación de riesgos y daños' },
  { codigo: '66220', descripcion: 'Actividades de agentes y corredores de seguros' },
  { codigo: '66290', descripcion: 'Otras actividades auxiliares de las actividades de seguros' },
  { codigo: '66300', descripcion: 'Actividades de administración de fondos' },
  // Actividades inmobiliarias
  { codigo: '68100', descripcion: 'Actividades inmobiliarias con bienes propios o arrendados' },
  { codigo: '68200', descripcion: 'Actividades inmobiliarias realizadas a cambio de una retribución' },
  // Actividades profesionales
  { codigo: '69100', descripcion: 'Actividades jurídicas' },
  { codigo: '69200', descripcion: 'Actividades de contabilidad, teneduría de libros y auditoría' },
  { codigo: '70100', descripcion: 'Actividades de oficinas centrales' },
  { codigo: '70200', descripcion: 'Actividades de consultoría de gestión empresarial' },
  { codigo: '71100', descripcion: 'Actividades de arquitectura e ingeniería' },
  { codigo: '71200', descripcion: 'Ensayos y análisis técnicos' },
  { codigo: '72100', descripcion: 'Investigación y desarrollo experimental en el campo de las ciencias naturales' },
  { codigo: '72200', descripcion: 'Investigación y desarrollo experimental en el campo de las ciencias sociales' },
  { codigo: '73100', descripcion: 'Publicidad' },
  { codigo: '73200', descripcion: 'Estudios de mercado y encuestas de opinión pública' },
  { codigo: '74100', descripcion: 'Actividades especializadas de diseño' },
  { codigo: '74200', descripcion: 'Actividades de fotografía' },
  { codigo: '74300', descripcion: 'Actividades de traducción e interpretación' },
  { codigo: '74900', descripcion: 'Otras actividades profesionales, científicas y técnicas' },
  { codigo: '75000', descripcion: 'Actividades veterinarias' },
  // Servicios administrativos
  { codigo: '77100', descripcion: 'Alquiler y arrendamiento de vehículos automotores' },
  { codigo: '77210', descripcion: 'Alquiler y arrendamiento de equipo recreativo y deportivo' },
  { codigo: '77220', descripcion: 'Alquiler de cintas de video y discos' },
  { codigo: '77290', descripcion: 'Alquiler y arrendamiento de otros efectos personales' },
  { codigo: '77300', descripcion: 'Alquiler y arrendamiento de maquinaria, equipo y bienes tangibles' },
  { codigo: '77400', descripcion: 'Arrendamiento de propiedad intelectual y productos similares' },
  { codigo: '78100', descripcion: 'Actividades de agencias de empleo' },
  { codigo: '78200', descripcion: 'Actividades de agencias de empleo temporal' },
  { codigo: '78300', descripcion: 'Otras actividades de dotación de recursos humanos' },
  { codigo: '79100', descripcion: 'Actividades de agencias de viajes y operadores turísticos' },
  { codigo: '79110', descripcion: 'Actividades de agencias de viajes' },
  { codigo: '79120', descripcion: 'Actividades de operadores turísticos' },
  { codigo: '79900', descripcion: 'Otros servicios de reservas y actividades conexas' },
  { codigo: '80100', descripcion: 'Actividades de seguridad privada' },
  { codigo: '80200', descripcion: 'Actividades de servicios de sistemas de seguridad' },
  { codigo: '80300', descripcion: 'Actividades de investigación' },
  { codigo: '81100', descripcion: 'Actividades combinadas de apoyo a instalaciones' },
  { codigo: '81210', descripcion: 'Limpieza general de edificios' },
  { codigo: '81290', descripcion: 'Otras actividades de limpieza de edificios e instalaciones industriales' },
  { codigo: '81300', descripcion: 'Actividades de paisajismo y servicios de mantenimiento conexos' },
  { codigo: '82110', descripcion: 'Actividades combinadas de servicios administrativos de oficina' },
  { codigo: '82190', descripcion: 'Fotocopiado, preparación de documentos y otras actividades' },
  { codigo: '82200', descripcion: 'Actividades de centros de llamadas' },
  { codigo: '82300', descripcion: 'Organización de convenciones y exposiciones comerciales' },
  { codigo: '82910', descripcion: 'Actividades de agencias de cobro y agencias de calificación crediticia' },
  { codigo: '82920', descripcion: 'Actividades de envasado y empaque' },
  { codigo: '82990', descripcion: 'Otras actividades de servicios de apoyo a las empresas' },
  // Educación
  { codigo: '85100', descripcion: 'Enseñanza preescolar' },
  { codigo: '85200', descripcion: 'Enseñanza primaria' },
  { codigo: '85310', descripcion: 'Enseñanza secundaria de formación general' },
  { codigo: '85320', descripcion: 'Enseñanza secundaria de formación técnica y profesional' },
  { codigo: '85410', descripcion: 'Enseñanza postsecundaria no terciaria' },
  { codigo: '85420', descripcion: 'Educación terciaria' },
  { codigo: '85491', descripcion: 'Enseñanza de idiomas' },
  { codigo: '85492', descripcion: 'Enseñanza de actividades culturales' },
  { codigo: '85493', descripcion: 'Enseñanza de actividades deportivas' },
  { codigo: '85499', descripcion: 'Otros tipos de enseñanza' },
  { codigo: '85500', descripcion: 'Actividades de apoyo a la enseñanza' },
  // Salud
  { codigo: '86100', descripcion: 'Actividades de hospitales' },
  { codigo: '86200', descripcion: 'Actividades de médicos y odontólogos' },
  { codigo: '86901', descripcion: 'Actividades de laboratorios clínicos' },
  { codigo: '86902', descripcion: 'Actividades de centros de diagnóstico médico' },
  { codigo: '86909', descripcion: 'Otras actividades relacionadas con la salud humana' },
  { codigo: '87100', descripcion: 'Actividades de atención de enfermería en instituciones' },
  { codigo: '87200', descripcion: 'Actividades de atención en instituciones para personas con discapacidad mental' },
  { codigo: '87300', descripcion: 'Actividades de atención en instituciones para personas de edad' },
  { codigo: '87900', descripcion: 'Otras actividades de atención en instituciones' },
  { codigo: '88100', descripcion: 'Actividades de asistencia social sin alojamiento para personas de edad' },
  { codigo: '88900', descripcion: 'Otras actividades de asistencia social sin alojamiento' },
  // Arte y entretenimiento
  { codigo: '90000', descripcion: 'Actividades creativas, artísticas y de entretenimiento' },
  { codigo: '91011', descripcion: 'Actividades de bibliotecas' },
  { codigo: '91012', descripcion: 'Actividades de archivos' },
  { codigo: '91020', descripcion: 'Actividades de museos' },
  { codigo: '91030', descripcion: 'Gestión de lugares y edificios históricos' },
  { codigo: '91040', descripcion: 'Actividades de jardines botánicos y zoológicos' },
  { codigo: '92000', descripcion: 'Actividades de juegos de azar y apuestas' },
  { codigo: '93110', descripcion: 'Gestión de instalaciones deportivas' },
  { codigo: '93120', descripcion: 'Actividades de clubes deportivos' },
  { codigo: '93130', descripcion: 'Actividades de gimnasios' },
  { codigo: '93190', descripcion: 'Otras actividades deportivas' },
  { codigo: '93210', descripcion: 'Actividades de parques de atracciones y parques temáticos' },
  { codigo: '93290', descripcion: 'Otras actividades recreativas y de esparcimiento' },
  // Otras actividades de servicios
  { codigo: '94110', descripcion: 'Actividades de asociaciones empresariales y de empleadores' },
  { codigo: '94120', descripcion: 'Actividades de asociaciones profesionales' },
  { codigo: '94200', descripcion: 'Actividades de sindicatos de empleados' },
  { codigo: '94910', descripcion: 'Actividades de organizaciones religiosas' },
  { codigo: '94920', descripcion: 'Actividades de organizaciones políticas' },
  { codigo: '94990', descripcion: 'Actividades de otras asociaciones' },
  { codigo: '95110', descripcion: 'Reparación de computadoras y equipo periférico' },
  { codigo: '95120', descripcion: 'Reparación de equipos de comunicaciones' },
  { codigo: '95210', descripcion: 'Reparación de aparatos electrónicos de consumo' },
  { codigo: '95220', descripcion: 'Reparación de aparatos domésticos y equipos de jardín' },
  { codigo: '95230', descripcion: 'Reparación de calzado y artículos de cuero' },
  { codigo: '95240', descripcion: 'Reparación de muebles y accesorios domésticos' },
  { codigo: '95290', descripcion: 'Reparación de otros efectos personales y enseres domésticos' },
  { codigo: '96010', descripcion: 'Lavado y limpieza de prendas de tela y de piel' },
  { codigo: '96020', descripcion: 'Peluquería y otros tratamientos de belleza' },
  { codigo: '96030', descripcion: 'Pompas fúnebres y actividades conexas' },
  { codigo: '96040', descripcion: 'Actividades de bienestar físico' },
  { codigo: '96090', descripcion: 'Otras actividades de servicios personales' },
];
